require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  StyleGuideBaseURL: https://rubystyle.guide
  Exclude:
    - bin/*
    - db/seeds.rb
    - db/schema.rb
    - spec/spec_helper.rb
    - config/environments/*.rb

Layout/LineLength:
  Max: 100
  Exclude:
    - Gemfile
    - Rakefile
    - config/{environments,initializers}/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
