version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
