version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data

  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.7.1
    ports:
    - 1080:1080
    - 1025:1025

volumes:
  postgres-data:
    driver: local
